### ISSUE TITLE
Destructive delete of mp3 files while editing ID3-tag over SMB

### ISSUE THREAD

**Issue by snattack** [alaahadid/AHD-ID3-Tag-Editor#1]
Not sure why this happened, but this is what I did:

1. Selected an mp3 located on a samba share.
2. Selected "Full Edit" button.
3. Did a change in the track number (removing the "/Portion in set"-part)
4. Pressing Save, initialized a progress bar that froze.
5. After waiting several minutes, I pressed "cancel", finding that the file was permanently deleted.

Clearly a very serious bug that needs investigation. Let me know what more you need to know.

**Comment by alaahadid** [comment]
I think the problem is about AITE is trying to save the file but doesn't have permission to write access, not necessary to the mp3 file. What AITE does:
1 make a temp file next to the original file called mp3file_temp which is an exact copy of the original file
2 it save the tag changes to this temp file
3 when save success into the temp, it deletes the original file
4 it rename the mp3file_temp file into the original file.
When something goes wrong with saving, simply it deletes the temp file and that's it. But when the original is deleted, it means it succeeded with tag saving into the temp file but fails to replace the original with it. In this case, AITE does something called emergency backup, which is to copy the temp file (mp3file_temp) into Temp folder in Windows (R) when it fails to replace the original file, the folder is something like:
`C:\Users\alaha\AppData\Local\Temp\AITE\`
`AppData` folder normally is hidden, you need to make sure that Windows Explorer show hidden files and folders.
Please check out this folder to look for deleted files. If they are not exist there, it means something serous happened.

This issue usually happens with me because of one of these reasons:
1 user permissions, AITE may have the permission to access mp3 files but when AITE make files it is blocked
2 media player is playing the original file and blocks it from write access

You can always check the temp folder for deleted files `C:\Users\alaha\AppData\Local\Temp\AITE\`

Also, in AITE there is a "Log Window" you can open from View menu, this window display messages about what's going on during processes such as saving tags. Taking a look at it may help understand what happened (simply open it before doing anything related to editing tags) also copying the messages and send them to me will help if this issue remains :)

**Comment by snattack** [comment]
Thanks for clarifying.

Wouldn't a better flow be:

1. Make temp-copy.
2. Edit original file, confirm edit worked.
3. If something goes wrong: log that with a flag and inform user that it didn't work, and that there's a temp file in the directory.
4. If nothing goes wrong, make safe backup (just in case), delete temp-file.

**Comment by alaahadid** [comment]
Agree, i think back then when the code is written, it was about making sure that the original file is not touched until the save process is 100% complete. I'll take a look ASAP and see what can be done about this.

**Comment by alaahadid** [comment]
Now AITE ([version 2.2.7818.27231 and later](https://github.com/alaahadid/AHD-ID3-Tag-Editor/releases/tag/v2.2.7818.27231)) saves backup file of each mp3 file before doing any save, if something went wrong with the save process, the backup file should be found next to the original file.
